spring:
  datasource:
    url: jdbc:mysql://47.106.244.103:3306/commodity_spike_system?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: LXD$donggua123
  redis:
    host: 47.106.244.103
    password: donggua$123
    port: 6379
    maxIdle: 100
    minIdle: 20
    maxTotal: 10000
    timeOut: 60000
  rabbitmq:
    host: 47.106.244.103
    port: 5672
    username: guest
    password: guest
    template:
      retry:
        initial-interval: 2s
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
    servlet:
      load-on-startup: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: top.showtan.commodity_spike_system.entity
server:
  port: 8080